/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/skills/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog */
        get: operations["catalog_internal_skills_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/skills/revoked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Revoked */
        get: operations["revoked_internal_skills_revoked_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/skills/{slug}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Versions */
        get: operations["versions_internal_skills__slug__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/skills/{slug}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_internal_skills__slug__versions__version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/mcp/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mcp Servers */
        get: operations["mcp_servers_internal_mcp_servers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/mcp/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mcp Reviews */
        get: operations["mcp_reviews_internal_mcp_reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Skills */
        get: operations["list_skills_config_skills_get"];
        put?: never;
        /** Upload Skill */
        post: operations["upload_skill_config_skills_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/skills/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Skill */
        get: operations["get_skill_config_skills__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/skills/{slug}/versions/{version}/files/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Published File */
        get: operations["read_published_file_config_skills__slug__versions__version__files__path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/skill-uploads/{upload_id}/files/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Upload File
         * @description 审查人看待审查的包。
         */
        get: operations["read_upload_file_config_skill_uploads__upload_id__files__path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/skill-uploads/{upload_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_config_skill_uploads__upload_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/skill-uploads/{upload_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject_config_skill_uploads__upload_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/skills/{slug}/versions/{version}/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Status */
        post: operations["change_status_config_skills__slug__versions__version___action__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/mcp/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Servers */
        get: operations["list_servers_config_mcp_servers_get"];
        put?: never;
        /** Create Server */
        post: operations["create_server_config_mcp_servers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/mcp/servers/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Server */
        get: operations["get_server_config_mcp_servers__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Server */
        patch: operations["patch_server_config_mcp_servers__name__patch"];
        trace?: never;
    };
    "/config/mcp/servers/{name}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reviews */
        get: operations["list_reviews_config_mcp_servers__name__reviews_get"];
        put?: never;
        /** Review Tool */
        post: operations["review_tool_config_mcp_servers__name__reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit */
        get: operations["list_audit_config_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditOut */
        AuditOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Actor */
            actor: string;
            /** Action */
            action: string;
            /** Target Kind */
            target_kind: string;
            /** Target Id */
            target_id: string;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            };
        };
        /** Body_upload_skill_config_skills_post */
        Body_upload_skill_config_skills_post: {
            /**
             * File
             * @description 技能包 zip
             */
            file: string;
            /**
             * Source
             * @default builtin
             * @enum {string}
             */
            source: "builtin" | "tenant" | "imported";
            /** Origin Url */
            origin_url?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** McpServerIn */
        McpServerIn: {
            /** Name */
            name: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Transport
             * @default streamable_http
             * @enum {string}
             */
            transport: "streamable_http" | "sse";
            /** Url */
            url: string;
            /** Headers */
            headers?: {
                [key: string]: string;
            };
            /**
             * Credential Scope
             * @default platform
             * @constant
             */
            credential_scope: "platform";
            /** Call Timeout S */
            call_timeout_s?: number | null;
            /**
             * Review Required
             * @default true
             */
            review_required: boolean;
            /**
             * Status
             * @default enabled
             * @enum {string}
             */
            status: "enabled" | "disabled";
        };
        /**
         * McpServerOut
         * @description 与运行时 McpServerConfig 同构的字段（name/url/transport/headers/enabled/
         *     call_timeout_s），外加注册表自己的元数据。headers 里只有占位符。
         */
        McpServerOut: {
            /** Name */
            name: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Transport */
            transport: string;
            /** Url */
            url: string;
            /** Headers */
            headers?: {
                [key: string]: string;
            };
            /**
             * Credential Scope
             * @default platform
             */
            credential_scope: string;
            /** Call Timeout S */
            call_timeout_s?: number | null;
            /**
             * Review Required
             * @default true
             */
            review_required: boolean;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Updated By */
            updated_by?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * McpServerPatch
         * @description name 不可改：它是工具前缀，改名 = 另一个 server。
         */
        McpServerPatch: {
            /** Display Name */
            display_name?: string | null;
            /** Description */
            description?: string | null;
            /** Transport */
            transport?: ("streamable_http" | "sse") | null;
            /** Url */
            url?: string | null;
            /** Headers */
            headers?: {
                [key: string]: string;
            } | null;
            /** Call Timeout S */
            call_timeout_s?: number | null;
            /** Review Required */
            review_required?: boolean | null;
            /** Status */
            status?: ("enabled" | "disabled") | null;
        };
        /** ReviewDecisionIn */
        ReviewDecisionIn: {
            /** Note */
            note: string;
        };
        /** RevokedSkill */
        RevokedSkill: {
            /** Slug */
            slug: string;
            /** Version */
            version: number;
            /** Reason */
            reason?: string | null;
            /** At */
            at?: string | null;
        };
        /**
         * SkillCatalogItem
         * @description 技能目录里的一项（编辑器选择器）。latest 只看 published。
         */
        SkillCatalogItem: {
            /** Slug */
            slug: string;
            /**
             * Source
             * @enum {string}
             */
            source: "builtin" | "tenant" | "imported";
            /** Latest */
            latest?: number | null;
            /** Description */
            description?: string | null;
            /** Has Scripts */
            has_scripts?: boolean | null;
            /** Versions */
            versions?: components["schemas"]["SkillVersionBrief"][];
        };
        /** SkillDetailOut */
        SkillDetailOut: {
            /** Slug */
            slug: string;
            /**
             * Source
             * @enum {string}
             */
            source: "builtin" | "tenant" | "imported";
            /** Origin Url */
            origin_url?: string | null;
            /** Created By */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Latest */
            latest?: number | null;
            /** Versions */
            versions?: components["schemas"]["SkillVersionAdminOut"][];
        };
        /** SkillFile */
        SkillFile: {
            /** Path */
            path: string;
            /** Size */
            size: number;
            /** Sha256 */
            sha256: string;
            /**
             * Executable
             * @default false
             */
            executable: boolean;
        };
        /**
         * SkillVersionAdminOut
         * @description 管理页看到的版本：含审查中 / 被拒的上传（运行时拿不到这些）。
         */
        SkillVersionAdminOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Version */
            version: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending_review" | "rejected" | "published" | "disabled" | "revoked";
            /** Description */
            description: string;
            /** Frontmatter */
            frontmatter?: {
                [key: string]: unknown;
            };
            /** Content Hash */
            content_hash: string;
            /** Size Bytes */
            size_bytes: number;
            /** File Count */
            file_count: number;
            /** Has Scripts */
            has_scripts: boolean;
            /** Files */
            files?: components["schemas"]["SkillFile"][];
            /** Scan Result */
            scan_result?: {
                [key: string]: unknown;
            };
            /** Uploaded By */
            uploaded_by: string;
            /** Reviewed By */
            reviewed_by?: string | null;
            /** Reviewed At */
            reviewed_at?: string | null;
            /** Review Note */
            review_note?: string | null;
            /** Status Reason */
            status_reason?: string | null;
            /** Published By */
            published_by?: string | null;
            /** Published At */
            published_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SkillVersionBrief */
        SkillVersionBrief: {
            /** Version */
            version: number;
            /**
             * Status
             * @enum {string}
             */
            status: "published" | "disabled" | "revoked";
        };
        /**
         * SkillVersionOut
         * @description 一个已发布（含已停用 / 已下架）的技能版本。
         *
         *     ★ 除 status / status_reason 外全部不可变：运行时据此永久缓存。
         */
        SkillVersionOut: {
            /** Slug */
            slug: string;
            /** Version */
            version: number;
            /**
             * Status
             * @enum {string}
             */
            status: "published" | "disabled" | "revoked";
            /** Description */
            description: string;
            /** Content Hash */
            content_hash: string;
            /** Size Bytes */
            size_bytes: number;
            /** File Count */
            file_count: number;
            /** Has Scripts */
            has_scripts: boolean;
            /** Files */
            files?: components["schemas"]["SkillFile"][];
            /**
             * Source
             * @default builtin
             * @enum {string}
             */
            source: "builtin" | "tenant" | "imported";
            /** Scan Result */
            scan_result?: {
                [key: string]: unknown;
            };
            /** Reviewed By */
            reviewed_by?: string | null;
            /** Reviewed At */
            reviewed_at?: string | null;
            /** Published By */
            published_by?: string | null;
            /** Published At */
            published_at?: string | null;
            /** Status Reason */
            status_reason?: string | null;
        };
        /** StatusChangeIn */
        StatusChangeIn: {
            /** Reason */
            reason?: string | null;
        };
        /** ToolReviewIn */
        ToolReviewIn: {
            /** Tool Name */
            tool_name: string;
            /** Digest */
            digest: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** ToolReviewOut */
        ToolReviewOut: {
            /** Server */
            server: string;
            /** Tool Name */
            tool_name: string;
            /** Digest */
            digest: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
            /** Decided By */
            decided_by: string;
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    catalog_internal_skills_catalog_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillCatalogItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoked_internal_skills_revoked_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokedSkill"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    versions_internal_skills__slug__versions_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillVersionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_internal_skills__slug__versions__version__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                slug: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillVersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mcp_servers_internal_mcp_servers_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpServerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mcp_reviews_internal_mcp_reviews_get: {
        parameters: {
            query: {
                server: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolReviewOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skills_config_skills_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetailOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_skill_config_skills_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_skill_config_skills_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillVersionAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_skill_config_skills__slug__get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_published_file_config_skills__slug__versions__version__files__path__get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                slug: string;
                version: number;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_upload_file_config_skill_uploads__upload_id__files__path__get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                upload_id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_config_skill_uploads__upload_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillVersionAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_config_skill_uploads__upload_id__reject_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillVersionAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_status_config_skills__slug__versions__version___action__post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                slug: string;
                version: number;
                action: "disable" | "enable" | "revoke" | "rescan";
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StatusChangeIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillVersionAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_servers_config_mcp_servers_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpServerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_server_config_mcp_servers_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["McpServerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpServerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_server_config_mcp_servers__name__get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpServerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_server_config_mcp_servers__name__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["McpServerPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpServerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reviews_config_mcp_servers__name__reviews_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolReviewOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_tool_config_mcp_servers__name__reviews_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolReviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_config_audit_get: {
        parameters: {
            query?: {
                target_kind?: string | null;
                target_id?: string | null;
                limit?: number;
            };
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
