/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description model_catalog ⋈ 网关 /v1/models 巡检结果。
         */
        get: operations["list_models_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tools
         * @description 内置工具 + 已接入 MCP 工具。bash 返回 available=false（决策 2）。
         */
        get: operations["list_tools_v1_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents */
        get: operations["list_agents_v1_agents_get"];
        put?: never;
        /**
         * Create Agent
         * @description 创建时同时写入 version 1，status=draft。
         */
        post: operations["create_agent_v1_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent */
        get: operations["get_agent_v1_agents__agent_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Agent
         * @description 归档语义：agent 置 archived、其会话一并归档。
         *
         *     不是物理删除 —— run.agent_version_id 需要 agent_version 存活才能解释历史会话（§5.4）。
         *     内置智能体返回 409。
         */
        delete: operations["delete_agent_v1_agents__agent_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Agent
         * @description ★ 保存即产生新版本并切换 current_version_id，不做原地更新（§5.4）。
         */
        patch: operations["update_agent_v1_agents__agent_id__patch"];
        trace?: never;
    };
    "/v1/agents/{agent_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Agent Status */
        post: operations["set_agent_status_v1_agents__agent_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agent Versions */
        get: operations["list_agent_versions_v1_agents__agent_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Threads */
        get: operations["list_threads_v1_threads_get"];
        put?: never;
        /** Create Thread */
        post: operations["create_thread_v1_threads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Thread */
        get: operations["get_thread_v1_threads__thread_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Thread
         * @description 真删：message / run / run_file 由 ON DELETE CASCADE 带走。
         */
        delete: operations["delete_thread_v1_threads__thread_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Thread
         * @description 改标题会把 title_source 置为 manual —— 自动生成不再覆盖它（决策 5）。
         */
        patch: operations["update_thread_v1_threads__thread_id__patch"];
        trace?: never;
    };
    "/v1/threads/{thread_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Files
         * @description 会话工作区里的文件 —— 直接列对象存储，包括 acp 子智能体在 Pod 里写的产物。
         */
        get: operations["list_files_v1_threads__thread_id__files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{thread_id}/files/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Preview
         * @description 签发文件预览令牌。站点在 GET /v1/previews/{token}/… 下（见 api/v1/previews.py）。
         */
        post: operations["create_preview_v1_threads__thread_id__files_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{thread_id}/files/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download File
         * @description 下载工作区里的一个文件（流式，不整个读进内存）。
         */
        get: operations["download_file_v1_threads__thread_id__files_download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{thread_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Run
         * @description 发消息 + 创建 run，立刻返回 run_id；事件走 GET /runs/{id}/events。
         *
         *     同一会话串行（Redis NX 锁），已有运行中的 run 时返回 409。
         *     带 Idempotency-Key 时重复提交返回同一个 run，不会变成两条消息（§11.2）。
         */
        post: operations["create_run_v1_threads__thread_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{thread_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Thread Events
         * @description 一条会话的 SSE 事件流 —— 该会话下**所有** run 的事件，含子智能体的。
         *
         *     与 `GET /runs/{id}/events` 的三处差别（doc/detail/suspension.html §04）：
         *
         *       · 永不自动结束。终态事件不再是关闭信号 —— 一轮跑完后面还有下一轮。
         *         这是子 run 的过程（含审批弹窗）能被看见的前提。
         *       · id 写 `thread_seq`（会话内单调），不是 run 内的 seq。
         *       · 首连只回放最近 N 条（sse_thread_replay_events）。带游标的重连不受
         *         此限 —— 那时要补的是缺口。
         *
         *     ★ 游标缺省值是 None 而不是 0，两者语义不同：None = 「我没有游标，给我
         *       默认窗口」，0 = 「从头给我」。用 0 当缺省会让每次打开老会话都全量回放。
         */
        get: operations["stream_thread_events_v1_threads__thread_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{thread_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Messages
         * @description 倒序分页，返回**完整原文** —— 上下文压缩只改写 checkpoint（§7.4）。
         */
        get: operations["list_messages_v1_threads__thread_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Trace
         * @description 一轮的归档轨迹（含子 run）—— 历史轮次的工具、委派、审批靠它在对话里重现。
         *
         *     ★ 与会话 SSE 流的分工：SSE 只回放最近一个窗口、只服务进行中的那一轮；
         *       已结束的轮次按需取这里，一轮一次，结果不会再变。
         */
        get: operations["get_run_trace_v1_runs__run_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Run
         * @description 写取消信号；engine 每步检查一次，到安全点后产出 run.cancelled。
         */
        post: operations["cancel_run_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pending Approvals
         * @description 该 run 上还没决策的确认项。
         *
         *     存在的理由是**刷新页面**：审批挂起时用户刷新，实时状态全没了。
         *     SSE 重连虽然会重放 approval.required，但那依赖 Redis 里的事件还在；
         *     这个端点直接查库，是更硬的恢复路径。
         */
        get: operations["list_pending_approvals_v1_runs__run_id__approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/approvals/{approval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide Approval
         * @description 批准或拒绝一次高风险工具调用（§12.2）。
         *
         *     拒绝**不终止 run** —— agent 会收到"用户拒绝"作为工具结果，
         *     可以换个方案继续，而不是整轮白跑。
         */
        post: operations["decide_approval_v1_runs__run_id__approvals__approval_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Memories
         * @description 列出**当前用户**的记忆。
         *
         *     ★ user_id 由服务端从会话取，**不接受参数传入**（§09）。Mem0 的
         *       filters 决定了能读到谁的记忆 —— 一旦它可以由调用方指定，就等于
         *       开了一个读取他人记忆的口子。
         */
        get: operations["list_memories_v1_memories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{memory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Memory
         * @description 删除单条。
         *
         *     ★ 先确认这条属于当前用户再删 —— Mem0 的 delete(memory_id) 不带作用域，
         *       直接透传等于任何人都能删别人的记忆。
         *
         *     ★ 措辞上**不承诺「彻底删除」**：delete() 到底是真把向量与原文清掉、
         *       还是只标记为不可见，属于 §12 第 7 项的待验证项。在验证之前对用户
         *       说「已彻底删除」是不诚实的 —— 而用户删记忆往往正是因为它敏感。
         */
        delete: operations["delete_memory_v1_memories__memory_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Skills
         * @description 技能目录（来自配置服务，经缓存）+ 引用数 + 近 7 天加载次数。编辑器选择器用。
         */
        get: operations["list_skills_v1_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Skill Usage */
        get: operations["skill_usage_v1_skills_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills/{slug}/references": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Skill References
         * @description 引用该技能的 agent（按当前版本）—— 停用 / 下架前必查。
         */
        get: operations["skill_references_v1_skills__slug__references_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mcp/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Mcp Servers
         * @description ★ 只读快照缓存，不触发发现：管理页不能被一个慢 server 拖住。
         */
        get: operations["list_mcp_servers_v1_mcp_servers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mcp/servers/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mcp Server */
        get: operations["get_mcp_server_v1_mcp_servers__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mcp/servers/{name}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Mcp Server
         * @description 强制重新发现。同一 server 10 秒内只执行一次。
         */
        post: operations["refresh_mcp_server_v1_mcp_servers__name__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentCreate */
        AgentCreate: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Avatar Key
             * @default general
             */
            avatar_key: string;
            spec: components["schemas"]["AgentSpecIn"];
        };
        /** AgentDetailOut */
        AgentDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Avatar Key */
            avatar_key: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "enabled" | "archived";
            /** Is Builtin */
            is_builtin: boolean;
            /** Version */
            version: number;
            /** Model */
            model: string;
            /** Tool Count */
            tool_count: number;
            /** Subagent Count */
            subagent_count: number;
            /**
             * Kind
             * @default native
             */
            kind: string;
            /**
             * Builtin Tool Count
             * @default 0
             */
            builtin_tool_count: number;
            /**
             * Skill Count
             * @default 0
             */
            skill_count: number;
            /**
             * Mcp Servers
             * @default []
             */
            mcp_servers: string[];
            /**
             * Subagents
             * @default []
             */
            subagents: {
                [key: string]: unknown;
            }[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Spec */
            spec: {
                [key: string]: unknown;
            };
        };
        /** AgentListOut */
        AgentListOut: {
            /** Data */
            data: components["schemas"]["AgentOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** AgentOut */
        AgentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Avatar Key */
            avatar_key: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "enabled" | "archived";
            /** Is Builtin */
            is_builtin: boolean;
            /** Version */
            version: number;
            /** Model */
            model: string;
            /** Tool Count */
            tool_count: number;
            /** Subagent Count */
            subagent_count: number;
            /**
             * Kind
             * @default native
             */
            kind: string;
            /**
             * Builtin Tool Count
             * @default 0
             */
            builtin_tool_count: number;
            /**
             * Skill Count
             * @default 0
             */
            skill_count: number;
            /**
             * Mcp Servers
             * @default []
             */
            mcp_servers: string[];
            /**
             * Subagents
             * @default []
             */
            subagents: {
                [key: string]: unknown;
            }[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * AgentSpecIn
         * @description agent_version.spec 的请求形态。slug / name 由 agent 行提供，不在这里重复。
         *
         *     ★ 快照纪律：新字段必须有默认值 —— agent_version.spec 是历史数据，
         *       加必填会让所有历史快照反序列化失败。守卫见
         *       tests/test_spec_snapshots.py。
         */
        AgentSpecIn: {
            /**
             * System Prompt
             * @default
             */
            system_prompt: string;
            model: components["schemas"]["ModelSpecIn"];
            /** Tool Names */
            tool_names?: string[];
            /** Subagents */
            subagents?: components["schemas"]["SubAgentSpecIn"][];
            /** Skills */
            skills?: components["schemas"]["SkillRefIn"][];
            limits?: components["schemas"]["LimitSpecIn"];
            compaction?: components["schemas"]["CompactionSpecIn"];
            /**
             * Kind
             * @default native
             * @enum {string}
             */
            kind: "native" | "acp";
            cli?: components["schemas"]["CliSpecIn"] | null;
            /** Mcp Tool Digests */
            mcp_tool_digests?: {
                [key: string]: string;
            };
            /**
             * Mcp Drift Policy
             * @default warn
             * @enum {string}
             */
            mcp_drift_policy: "warn" | "block";
        };
        /** AgentStatusUpdate */
        AgentStatusUpdate: {
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "enabled" | "archived";
        };
        /**
         * AgentUpdate
         * @description PATCH 语义：保存即产生新版本，不做原地更新（文档 §11.1 / §5.4）。
         *
         *     slug 创建后不可改 —— 它是 API 引用键。
         */
        AgentUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Avatar Key */
            avatar_key?: string | null;
            spec?: components["schemas"]["AgentSpecIn"] | null;
        };
        /** AgentVersionListOut */
        AgentVersionListOut: {
            /** Data */
            data: components["schemas"]["AgentVersionOut"][];
        };
        /** AgentVersionOut */
        AgentVersionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Version */
            version: number;
            /** Spec */
            spec: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ApprovalDecision
         * @description §12.2：批准或拒绝。expired 由服务端判定，不接受客户端提交。
         */
        ApprovalDecision: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
        };
        /** ApprovalOut */
        ApprovalOut: {
            /**
             * Approval Id
             * Format: uuid
             */
            approval_id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Decision */
            decision: string;
        };
        /**
         * CliSpecIn
         * @description acp agent 的 CLI 形态。快照纪律：除 cli_type 外都要有默认值。
         */
        CliSpecIn: {
            /** Cli Type */
            cli_type: string;
            /**
             * Adapter
             * @default
             */
            adapter: string;
            /**
             * Image
             * @default
             */
            image: string;
            /**
             * Permission Mode
             * @default auto
             * @enum {string}
             */
            permission_mode: "manual" | "accept_edits" | "auto" | "plan";
        };
        /** CompactionSpecIn */
        CompactionSpecIn: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Trigger Ratio
             * @default 0.75
             */
            trigger_ratio: number;
            /**
             * Target Ratio
             * @default 0.4
             */
            target_ratio: number;
            /**
             * Keep Recent Turns
             * @default 3
             */
            keep_recent_turns: number;
            /**
             * Summarizer Model
             * @default claude-haiku-4-5
             */
            summarizer_model: string;
        };
        /**
         * EventType
         * @enum {string}
         */
        EventType: "run.started" | "run.finished" | "run.failed" | "run.cancelled" | "run.suspended" | "thinking.delta" | "message.delta" | "message.completed" | "todos.updated" | "tool.started" | "tool.completed" | "tool.failed" | "subagent.started" | "subagent.step" | "subagent.finished" | "file.written" | "file.deleted" | "usage.updated" | "approval.required" | "context.compacted" | "session.lost" | "agent.mode" | "thread.title_generated" | "skill.loaded" | "skill.skipped" | "mcp.tool_drift";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LimitSpecIn */
        LimitSpecIn: {
            /**
             * Max Steps
             * @default 40
             */
            max_steps: number;
            /**
             * Timeout S
             * @default 300
             */
            timeout_s: number;
            /**
             * Max Total Tokens
             * @default 500000
             */
            max_total_tokens: number;
            /**
             * Max Subagent Depth
             * @default 2
             */
            max_subagent_depth: number;
            /**
             * Tool Concurrency
             * @default 4
             */
            tool_concurrency: number;
            /** Require Approval For */
            require_approval_for?: string[];
        };
        /** McpServerDetailOut */
        McpServerDetailOut: {
            /** Name */
            name: string;
            /** Url */
            url: string;
            /** Transport */
            transport: string;
            /** Credential Scope */
            credential_scope: string;
            /** Headers */
            headers: {
                [key: string]: string;
            };
            /** Call Timeout S */
            call_timeout_s: number | null;
            /** Enabled */
            enabled: boolean;
            /** Review Required */
            review_required: boolean;
            /** Status */
            status: string;
            /** Error */
            error?: string | null;
            /**
             * Tools Count
             * @default 0
             */
            tools_count: number;
            /**
             * Invalid Tools
             * @default 0
             */
            invalid_tools: number;
            /**
             * Pending Review
             * @default 0
             */
            pending_review: number;
            /** Content Hash */
            content_hash?: string | null;
            /** Fetched At */
            fetched_at?: string | null;
            /** Changed At */
            changed_at?: string | null;
            /**
             * References
             * @default 0
             */
            references: number;
            /** Tools */
            tools?: components["schemas"]["McpToolOut"][];
            /** Removed Tools */
            removed_tools?: string[];
            /** Referenced By */
            referenced_by?: {
                [key: string]: unknown;
            }[];
        };
        /** McpServerListOut */
        McpServerListOut: {
            /** Registry */
            registry: string;
            /** Data */
            data: components["schemas"]["McpServerSummary"][];
        };
        /** McpServerSummary */
        McpServerSummary: {
            /** Name */
            name: string;
            /** Url */
            url: string;
            /** Transport */
            transport: string;
            /** Credential Scope */
            credential_scope: string;
            /** Headers */
            headers: {
                [key: string]: string;
            };
            /** Call Timeout S */
            call_timeout_s: number | null;
            /** Enabled */
            enabled: boolean;
            /** Review Required */
            review_required: boolean;
            /** Status */
            status: string;
            /** Error */
            error?: string | null;
            /**
             * Tools Count
             * @default 0
             */
            tools_count: number;
            /**
             * Invalid Tools
             * @default 0
             */
            invalid_tools: number;
            /**
             * Pending Review
             * @default 0
             */
            pending_review: number;
            /** Content Hash */
            content_hash?: string | null;
            /** Fetched At */
            fetched_at?: string | null;
            /** Changed At */
            changed_at?: string | null;
            /**
             * References
             * @default 0
             */
            references: number;
        };
        /** McpToolOut */
        McpToolOut: {
            /** Name */
            name: string;
            /** Id */
            id: string;
            /** Model Name */
            model_name: string | null;
            /** Description */
            description: string;
            /** Digest */
            digest: string;
            /** Issues */
            issues?: string[];
            /** Review Status */
            review_status: string;
            /** Change */
            change?: string | null;
            /** Previous Description */
            previous_description?: string | null;
        };
        /** MemoryListOut */
        MemoryListOut: {
            /** Data */
            data: components["schemas"]["MemoryOut"][];
        };
        /** MemoryOut */
        MemoryOut: {
            /** Id */
            id: string;
            /** Memory */
            memory: string;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Workspace */
            workspace?: string | null;
            /** Source Session */
            source_session?: string | null;
            /** Source Run */
            source_run?: string | null;
        };
        /**
         * MessageListOut
         * @description 倒序分页：最新的在前，前端向上滚动加载更旧的。
         */
        MessageListOut: {
            /** Data */
            data: components["schemas"]["MessageOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** MessageOut */
        MessageOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /** Run Id */
            run_id: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: {
                [key: string]: unknown;
            }[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ModelInfo */
        ModelInfo: {
            /** Model */
            model: string;
            /** Provider */
            provider: string;
            /** Display Name */
            display_name: string;
            /** Context Window */
            context_window: number;
            /** Max Output Tokens */
            max_output_tokens: number;
            /** Supports Thinking */
            supports_thinking: boolean;
            /** Supports Adaptive Thinking */
            supports_adaptive_thinking: boolean;
            /** Supports Effort */
            supports_effort: boolean;
            /** Supports Cache */
            supports_cache: boolean;
            /** Supports Temperature */
            supports_temperature: boolean;
            /** Min Cacheable Tokens */
            min_cacheable_tokens: number;
            /**
             * Is Available
             * @description 网关巡检结果；false 时编辑器标灰不可选
             */
            is_available: boolean;
        };
        /** ModelListResponse */
        ModelListResponse: {
            /** Data */
            data: components["schemas"]["ModelInfo"][];
            /**
             * Gateway Reachable
             * @description false 表示巡检失败，is_available 退化为 catalog 中的存量值
             */
            gateway_reachable: boolean;
        };
        /** ModelSpecIn */
        ModelSpecIn: {
            /** Model */
            model: string;
            /**
             * Provider
             * @default anthropic
             * @enum {string}
             */
            provider: "anthropic" | "openai";
            /** Effort */
            effort?: ("max" | "xhigh" | "high" | "medium" | "low") | null;
            /**
             * Thinking
             * @default auto
             * @enum {string}
             */
            thinking: "auto" | "adaptive" | "off";
            /**
             * Max Output Tokens
             * @default 16384
             */
            max_output_tokens: number;
            /**
             * Prompt Cache
             * @default true
             */
            prompt_cache: boolean;
            /** Temperature */
            temperature?: number | null;
        };
        /**
         * PendingApproval
         * @description 挂起中的确认。刷新页面后前端靠它把弹窗恢复出来。
         */
        PendingApproval: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Tool Name */
            tool_name: string;
            /** Args */
            args: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PendingApprovalList */
        PendingApprovalList: {
            /** Data */
            data: components["schemas"]["PendingApproval"][];
        };
        /**
         * PreviewSessionOut
         * @description 文件预览站点的入口。base_url 以 / 结尾，文件地址 = base_url + 逐段编码的路径。
         */
        PreviewSessionOut: {
            /** Base Url */
            base_url: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** RunAccepted */
        RunAccepted: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "interrupted" | "awaiting_approval" | "suspended";
        };
        /**
         * RunCreate
         * @description 发消息 + 创建 run（文档 §11.2）。
         */
        RunCreate: {
            /**
             * Content
             * @description Anthropic content blocks，如 [{'type':'text','text':'...'}]
             */
            content: {
                [key: string]: unknown;
            }[];
        };
        /** RunOut */
        RunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /** Parent Run Id */
            parent_run_id?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "interrupted" | "awaiting_approval" | "suspended";
            /** Error Kind */
            error_kind: string | null;
            /** Error Message */
            error_message: string | null;
            /** Last Seq */
            last_seq: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cache Read Tokens */
            cache_read_tokens: number;
            /** Thinking Tokens */
            thinking_tokens: number;
            /** Total Tokens */
            total_tokens: number;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * RunTraceOut
         * @description 一轮的归档轨迹（含子 run），按 thread_seq 正序。
         *
         *     ★ 不含 message.delta（归档时就滤掉了），正文由 message.completed 一次给全。
         *     ★ 空列表 = 归档已被清理，前端退回只显示消息正文。
         */
        RunTraceOut: {
            /** Data */
            data: components["schemas"]["TraceEvent"][];
        };
        /** SkillListItem */
        SkillListItem: {
            /** Slug */
            slug: string;
            /** Source */
            source: string;
            /** Latest */
            latest?: number | null;
            /** Description */
            description?: string | null;
            /** Has Scripts */
            has_scripts?: boolean | null;
            /** Versions */
            versions?: components["schemas"]["SkillVersionBrief"][];
            /**
             * References
             * @default 0
             */
            references: number;
            /**
             * Loads 7D
             * @default 0
             */
            loads_7d: number;
        };
        /** SkillListOut */
        SkillListOut: {
            /** Directory Configured */
            directory_configured: boolean;
            /** Data */
            data: components["schemas"]["SkillListItem"][];
        };
        /**
         * SkillRefIn
         * @description agent 引用一个技能。
         *
         *     ★ version=None 只在**请求体**里合法，表示"用当前版本"。服务层在落库
         *       前解析成具体版本号 —— 于是存进 agent_version.spec 的永远是确定版本，
         *       历史 run 可精确复现，技能升级不会悄悄改变已有配置的含义。
         *
         *     ★ 快照纪律（tests/test_spec_snapshots.py）：必填集合只有 slug，
         *       version 必须有默认值。
         */
        SkillRefIn: {
            /** Slug */
            slug: string;
            /** Version */
            version?: number | null;
        };
        /** SkillReference */
        SkillReference: {
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Agent Slug */
            agent_slug: string;
            /** Agent Name */
            agent_name: string;
            /** Agent Version */
            agent_version: number;
            /** Subagent */
            subagent?: string | null;
            /** Skill Version */
            skill_version: number;
            /**
             * Active Threads
             * @default 0
             */
            active_threads: number;
        };
        /** SkillReferencesOut */
        SkillReferencesOut: {
            /** Data */
            data: components["schemas"]["SkillReference"][];
        };
        /** SkillUsageItem */
        SkillUsageItem: {
            /** Slug */
            slug: string;
            /** Version */
            version: number;
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Loads */
            loads: number;
            /** Completed Runs */
            completed_runs: number;
        };
        /** SkillUsageOut */
        SkillUsageOut: {
            /** Days */
            days: number;
            /** Data */
            data: components["schemas"]["SkillUsageItem"][];
        };
        /** SkillVersionBrief */
        SkillVersionBrief: {
            /** Version */
            version: number;
            /**
             * Status
             * @enum {string}
             */
            status: "published" | "disabled" | "revoked";
        };
        /** SubAgentSpecIn */
        SubAgentSpecIn: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * System Prompt
             * @default
             */
            system_prompt: string;
            model: components["schemas"]["ModelSpecIn"];
            /** Tool Names */
            tool_names?: string[];
            /** Skills */
            skills?: components["schemas"]["SkillRefIn"][];
            /**
             * Session Mode
             * @default persistent
             * @enum {string}
             */
            session_mode: "persistent" | "ephemeral";
            compaction?: components["schemas"]["CompactionSpecIn"] | null;
            /**
             * Kind
             * @default native
             * @enum {string}
             */
            kind: "native" | "acp";
            cli?: components["schemas"]["CliSpecIn"] | null;
            /** Mcp Tool Digests */
            mcp_tool_digests?: {
                [key: string]: string;
            };
            /**
             * Mcp Drift Policy
             * @default warn
             * @enum {string}
             */
            mcp_drift_policy: "warn" | "block";
            /** Source Agent Id */
            source_agent_id?: string | null;
        };
        /** ThreadCreate */
        ThreadCreate: {
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /**
             * Title
             * @default
             */
            title: string;
        };
        /** ThreadListOut */
        ThreadListOut: {
            /** Data */
            data: components["schemas"]["ThreadOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ThreadOut */
        ThreadOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Agent Slug */
            agent_slug: string;
            /** Agent Name */
            agent_name: string;
            /** Agent Avatar Key */
            agent_avatar_key: string;
            /** Title */
            title: string;
            /**
             * Title Source
             * @enum {string}
             */
            title_source: "pending" | "generated" | "fallback" | "manual";
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "archived" | "ephemeral";
            /** Parent Thread Id */
            parent_thread_id?: string | null;
            /** Subagent Name */
            subagent_name?: string | null;
            /**
             * Subagent Thread Count
             * @default 0
             */
            subagent_thread_count: number;
            /** Active Run Id */
            active_run_id?: string | null;
            last_run?: components["schemas"]["ThreadRunState"] | null;
            /** Message Count */
            message_count: number;
            /** Compact Count */
            compact_count: number;
            /** Latest State */
            latest_state: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ThreadRunState
         * @description 会话最近一个 run 的状态 —— 列表上的「运行中 / 待审批 / 等待子智能体 / 失败」。
         */
        ThreadRunState: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /**
             * Waiting
             * @default []
             */
            waiting: string[];
            /**
             * Needs Approval
             * @default false
             */
            needs_approval: boolean;
        };
        /**
         * ThreadUpdate
         * @description 重命名会把 title_source 置为 manual —— 之后永不被自动生成覆盖（决策 5）。
         */
        ThreadUpdate: {
            /** Title */
            title?: string | null;
            /** Status */
            status?: ("active" | "archived") | null;
        };
        /** ToolInfo */
        ToolInfo: {
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Display Name */
            display_name: string;
            /** Description */
            description: string;
            /** Available */
            available: boolean;
            /** Note */
            note?: string | null;
            /**
             * Model Tool Names
             * @default []
             */
            model_tool_names: string[];
            /** Server */
            server?: string | null;
            /** Digest */
            digest?: string | null;
            /** Review Status */
            review_status?: string | null;
        };
        /** ToolListResponse */
        ToolListResponse: {
            /** Data */
            data: components["schemas"]["ToolInfo"][];
        };
        /** TraceEvent */
        TraceEvent: {
            /**
             * Seq
             * @description run 内单调递增
             */
            seq: number;
            /**
             * Thread Seq
             * @description thread 内单调递增，thread 流的游标
             * @default 0
             */
            thread_seq: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            type: components["schemas"]["EventType"];
            /**
             * Depth
             * @description 0=主 agent，1=子 agent，前端缩进用
             * @default 0
             */
            depth: number;
            /** Data */
            data?: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkspaceFile */
        WorkspaceFile: {
            /** Path */
            path: string;
            /** Size */
            size: number;
            /** Modified At */
            modified_at?: string | null;
            /** Etag */
            etag?: string | null;
        };
        /**
         * WorkspaceFilesOut
         * @description 会话工作区里的文件（右侧「文件」面板）。子会话看的是父会话的工作区（共享）。
         */
        WorkspaceFilesOut: {
            /** Configured */
            configured: boolean;
            /** Data */
            data: components["schemas"]["WorkspaceFile"][];
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_models_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelListResponse"];
                };
            };
        };
    };
    list_tools_v1_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolListResponse"];
                };
            };
        };
    };
    list_agents_v1_agents_get: {
        parameters: {
            query?: {
                /** @description 搜索名称 / 标识 / 描述 */
                q?: string | null;
                status?: string | null;
                /** @description 按模型 id 过滤 */
                model?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_v1_agents_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_v1_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_agent_v1_agents__agent_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_agent_v1_agents__agent_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_agent_status_v1_agents__agent_id__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agent_versions_v1_agents__agent_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentVersionListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_threads_v1_threads_get: {
        parameters: {
            query?: {
                status?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_thread_v1_threads_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThreadCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thread_v1_threads__thread_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_thread_v1_threads__thread_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_thread_v1_threads__thread_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThreadUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_files_v1_threads__thread_id__files_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceFilesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_preview_v1_threads__thread_id__files_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_file_v1_threads__thread_id__files_download_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_v1_threads__thread_id__runs_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_thread_events_v1_threads__thread_id__events_get: {
        parameters: {
            query?: {
                after_seq?: number | null;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_v1_threads__thread_id__messages_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_trace_v1_runs__run_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunTraceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pending_approvals_v1_runs__run_id__approvals_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingApprovalList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_approval_v1_runs__run_id__approvals__approval_id__post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path: {
                run_id: string;
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_memories_v1_memories_get: {
        parameters: {
            query?: {
                limit?: number;
                workspace?: string | null;
                source_session?: string | null;
            };
            header?: {
                "X-User-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_memory_v1_memories__memory_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path: {
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skills_v1_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillListOut"];
                };
            };
        };
    };
    skill_usage_v1_skills_usage_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillUsageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    skill_references_v1_skills__slug__references_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillReferencesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mcp_servers_v1_mcp_servers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpServerListOut"];
                };
            };
        };
    };
    get_mcp_server_v1_mcp_servers__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpServerDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_mcp_server_v1_mcp_servers__name__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpServerDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
