/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description model_catalog ⋈ 网关 /v1/models 巡检结果。
         */
        get: operations["list_models_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tools
         * @description 内置工具 + 已接入 MCP 工具。bash 返回 available=false（决策 2）。
         */
        get: operations["list_tools_v1_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents */
        get: operations["list_agents_v1_agents_get"];
        put?: never;
        /**
         * Create Agent
         * @description 创建时同时写入 version 1，status=draft。
         */
        post: operations["create_agent_v1_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent */
        get: operations["get_agent_v1_agents__agent_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Agent
         * @description 归档语义：agent 置 archived、其会话一并归档。
         *
         *     不是物理删除 —— run.agent_version_id 需要 agent_version 存活才能解释历史会话（§5.4）。
         *     内置智能体返回 409。
         */
        delete: operations["delete_agent_v1_agents__agent_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Agent
         * @description ★ 保存即产生新版本并切换 current_version_id，不做原地更新（§5.4）。
         */
        patch: operations["update_agent_v1_agents__agent_id__patch"];
        trace?: never;
    };
    "/v1/agents/{agent_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Agent Status */
        post: operations["set_agent_status_v1_agents__agent_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agent Versions */
        get: operations["list_agent_versions_v1_agents__agent_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Threads */
        get: operations["list_threads_v1_threads_get"];
        put?: never;
        /** Create Thread */
        post: operations["create_thread_v1_threads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Thread */
        get: operations["get_thread_v1_threads__thread_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Thread
         * @description 真删：message / run / run_file 由 ON DELETE CASCADE 带走。
         */
        delete: operations["delete_thread_v1_threads__thread_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Thread
         * @description 改标题会把 title_source 置为 manual —— 自动生成不再覆盖它（决策 5）。
         */
        patch: operations["update_thread_v1_threads__thread_id__patch"];
        trace?: never;
    };
    "/v1/threads/{thread_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Run
         * @description 发消息 + 创建 run，立刻返回 run_id；事件走 GET /runs/{id}/events。
         *
         *     同一会话串行（Redis NX 锁），已有运行中的 run 时返回 409。
         *     带 Idempotency-Key 时重复提交返回同一个 run，不会变成两条消息（§11.2）。
         */
        post: operations["create_run_v1_threads__thread_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{thread_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Messages
         * @description 倒序分页，返回**完整原文** —— 上下文压缩只改写 checkpoint（§7.4）。
         */
        get: operations["list_messages_v1_threads__thread_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Run
         * @description 写取消信号；engine 每步检查一次，到安全点后产出 run.cancelled。
         */
        post: operations["cancel_run_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pending Approvals
         * @description 该 run 上还没决策的确认项。
         *
         *     存在的理由是**刷新页面**：审批挂起时用户刷新，实时状态全没了。
         *     SSE 重连虽然会重放 approval.required，但那依赖 Redis 里的事件还在；
         *     这个端点直接查库，是更硬的恢复路径。
         */
        get: operations["list_pending_approvals_v1_runs__run_id__approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/approvals/{approval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide Approval
         * @description 批准或拒绝一次高风险工具调用（§12.2）。
         *
         *     拒绝**不终止 run** —— agent 会收到"用户拒绝"作为工具结果，
         *     可以换个方案继续，而不是整轮白跑。
         */
        post: operations["decide_approval_v1_runs__run_id__approvals__approval_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Run Events
         * @description SSE 事件流。
         *
         *     断线重连：浏览器 EventSource 自动带 Last-Event-ID（即上次收到的 seq），
         *     服务端据此补发缺失部分再续读 —— 前端不需要写重连逻辑（§10.2）。
         *     after_seq 查询参数供非浏览器客户端使用。
         */
        get: operations["stream_run_events_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentCreate */
        AgentCreate: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Avatar Key
             * @default general
             */
            avatar_key: string;
            spec: components["schemas"]["AgentSpecIn"];
        };
        /** AgentDetailOut */
        AgentDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Avatar Key */
            avatar_key: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "enabled" | "archived";
            /** Is Builtin */
            is_builtin: boolean;
            /** Version */
            version: number;
            /** Model */
            model: string;
            /** Tool Count */
            tool_count: number;
            /** Subagent Count */
            subagent_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Spec */
            spec: {
                [key: string]: unknown;
            };
        };
        /** AgentListOut */
        AgentListOut: {
            /** Data */
            data: components["schemas"]["AgentOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** AgentOut */
        AgentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Avatar Key */
            avatar_key: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "enabled" | "archived";
            /** Is Builtin */
            is_builtin: boolean;
            /** Version */
            version: number;
            /** Model */
            model: string;
            /** Tool Count */
            tool_count: number;
            /** Subagent Count */
            subagent_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * AgentSpecIn
         * @description agent_version.spec 的请求形态。slug / name 由 agent 行提供，不在这里重复。
         *
         *     ★ 快照纪律：新字段必须有默认值 —— agent_version.spec 是历史数据，
         *       加必填会让所有历史快照反序列化失败。守卫见
         *       tests/test_spec_snapshots.py。
         */
        AgentSpecIn: {
            /**
             * System Prompt
             * @default
             */
            system_prompt: string;
            model: components["schemas"]["ModelSpecIn"];
            /** Tool Names */
            tool_names?: string[];
            /** Subagents */
            subagents?: components["schemas"]["SubAgentSpecIn"][];
            /** Skills */
            skills?: components["schemas"]["SkillRefIn"][];
            limits?: components["schemas"]["LimitSpecIn"];
            compaction?: components["schemas"]["CompactionSpecIn"];
            /**
             * Kind
             * @default native
             * @enum {string}
             */
            kind: "native" | "acp";
            cli?: components["schemas"]["CliSpecIn"] | null;
        };
        /** AgentStatusUpdate */
        AgentStatusUpdate: {
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "enabled" | "archived";
        };
        /**
         * AgentUpdate
         * @description PATCH 语义：保存即产生新版本，不做原地更新（文档 §11.1 / §5.4）。
         *
         *     slug 创建后不可改 —— 它是 API 引用键。
         */
        AgentUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Avatar Key */
            avatar_key?: string | null;
            spec?: components["schemas"]["AgentSpecIn"] | null;
        };
        /** AgentVersionListOut */
        AgentVersionListOut: {
            /** Data */
            data: components["schemas"]["AgentVersionOut"][];
        };
        /** AgentVersionOut */
        AgentVersionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Version */
            version: number;
            /** Spec */
            spec: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ApprovalDecision
         * @description §12.2：批准或拒绝。expired 由服务端判定，不接受客户端提交。
         */
        ApprovalDecision: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
        };
        /** ApprovalOut */
        ApprovalOut: {
            /**
             * Approval Id
             * Format: uuid
             */
            approval_id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Decision */
            decision: string;
        };
        /**
         * CliSpecIn
         * @description acp agent 的 CLI 形态。快照纪律：除 cli_type 外都要有默认值。
         */
        CliSpecIn: {
            /** Cli Type */
            cli_type: string;
            /**
             * Adapter
             * @default
             */
            adapter: string;
            /**
             * Image
             * @default
             */
            image: string;
        };
        /** CompactionSpecIn */
        CompactionSpecIn: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Trigger Ratio
             * @default 0.75
             */
            trigger_ratio: number;
            /**
             * Target Ratio
             * @default 0.4
             */
            target_ratio: number;
            /**
             * Keep Recent Turns
             * @default 3
             */
            keep_recent_turns: number;
            /**
             * Summarizer Model
             * @default claude-haiku-4-5
             */
            summarizer_model: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LimitSpecIn */
        LimitSpecIn: {
            /**
             * Max Steps
             * @default 40
             */
            max_steps: number;
            /**
             * Timeout S
             * @default 300
             */
            timeout_s: number;
            /**
             * Max Total Tokens
             * @default 500000
             */
            max_total_tokens: number;
            /**
             * Max Subagent Depth
             * @default 2
             */
            max_subagent_depth: number;
            /**
             * Tool Concurrency
             * @default 4
             */
            tool_concurrency: number;
            /** Require Approval For */
            require_approval_for?: string[];
        };
        /**
         * MessageListOut
         * @description 倒序分页：最新的在前，前端向上滚动加载更旧的。
         */
        MessageListOut: {
            /** Data */
            data: components["schemas"]["MessageOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** MessageOut */
        MessageOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /** Run Id */
            run_id: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: {
                [key: string]: unknown;
            }[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ModelInfo */
        ModelInfo: {
            /** Model */
            model: string;
            /** Provider */
            provider: string;
            /** Display Name */
            display_name: string;
            /** Context Window */
            context_window: number;
            /** Max Output Tokens */
            max_output_tokens: number;
            /** Supports Thinking */
            supports_thinking: boolean;
            /** Supports Adaptive Thinking */
            supports_adaptive_thinking: boolean;
            /** Supports Effort */
            supports_effort: boolean;
            /** Supports Cache */
            supports_cache: boolean;
            /** Supports Temperature */
            supports_temperature: boolean;
            /** Min Cacheable Tokens */
            min_cacheable_tokens: number;
            /**
             * Is Available
             * @description 网关巡检结果；false 时编辑器标灰不可选
             */
            is_available: boolean;
        };
        /** ModelListResponse */
        ModelListResponse: {
            /** Data */
            data: components["schemas"]["ModelInfo"][];
            /**
             * Gateway Reachable
             * @description false 表示巡检失败，is_available 退化为 catalog 中的存量值
             */
            gateway_reachable: boolean;
        };
        /** ModelSpecIn */
        ModelSpecIn: {
            /** Model */
            model: string;
            /**
             * Provider
             * @default anthropic
             * @enum {string}
             */
            provider: "anthropic" | "openai";
            /** Effort */
            effort?: ("max" | "xhigh" | "high" | "medium" | "low") | null;
            /**
             * Thinking
             * @default auto
             * @enum {string}
             */
            thinking: "auto" | "adaptive" | "off";
            /**
             * Max Output Tokens
             * @default 16384
             */
            max_output_tokens: number;
            /**
             * Prompt Cache
             * @default true
             */
            prompt_cache: boolean;
            /** Temperature */
            temperature?: number | null;
        };
        /**
         * PendingApproval
         * @description 挂起中的确认。刷新页面后前端靠它把弹窗恢复出来。
         */
        PendingApproval: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Tool Name */
            tool_name: string;
            /** Args */
            args: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PendingApprovalList */
        PendingApprovalList: {
            /** Data */
            data: components["schemas"]["PendingApproval"][];
        };
        /** RunAccepted */
        RunAccepted: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "interrupted" | "awaiting_approval";
        };
        /**
         * RunCreate
         * @description 发消息 + 创建 run（文档 §11.2）。
         */
        RunCreate: {
            /**
             * Content
             * @description Anthropic content blocks，如 [{'type':'text','text':'...'}]
             */
            content: {
                [key: string]: unknown;
            }[];
        };
        /** RunOut */
        RunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /** Parent Run Id */
            parent_run_id?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "interrupted" | "awaiting_approval";
            /** Error Kind */
            error_kind: string | null;
            /** Error Message */
            error_message: string | null;
            /** Last Seq */
            last_seq: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cache Read Tokens */
            cache_read_tokens: number;
            /** Thinking Tokens */
            thinking_tokens: number;
            /** Total Tokens */
            total_tokens: number;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SkillRefIn
         * @description agent 引用一个技能。
         *
         *     ★ version=None 只在**请求体**里合法，表示"用当前版本"。服务层在落库
         *       前解析成具体版本号 —— 于是存进 agent_version.spec 的永远是确定版本，
         *       历史 run 可精确复现，技能升级不会悄悄改变已有配置的含义。
         *
         *     ★ 快照纪律（tests/test_spec_snapshots.py）：必填集合只有 slug，
         *       version 必须有默认值。
         */
        SkillRefIn: {
            /** Slug */
            slug: string;
            /** Version */
            version?: number | null;
        };
        /** SubAgentSpecIn */
        SubAgentSpecIn: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * System Prompt
             * @default
             */
            system_prompt: string;
            model: components["schemas"]["ModelSpecIn"];
            /** Tool Names */
            tool_names?: string[];
            /** Skills */
            skills?: components["schemas"]["SkillRefIn"][];
            /**
             * Session Mode
             * @default persistent
             * @enum {string}
             */
            session_mode: "persistent" | "ephemeral";
            compaction?: components["schemas"]["CompactionSpecIn"] | null;
            /**
             * Kind
             * @default native
             * @enum {string}
             */
            kind: "native" | "acp";
            cli?: components["schemas"]["CliSpecIn"] | null;
            /** Source Agent Id */
            source_agent_id?: string | null;
        };
        /** ThreadCreate */
        ThreadCreate: {
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /**
             * Title
             * @default
             */
            title: string;
        };
        /** ThreadListOut */
        ThreadListOut: {
            /** Data */
            data: components["schemas"]["ThreadOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ThreadOut */
        ThreadOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Agent Slug */
            agent_slug: string;
            /** Agent Name */
            agent_name: string;
            /** Agent Avatar Key */
            agent_avatar_key: string;
            /** Title */
            title: string;
            /**
             * Title Source
             * @enum {string}
             */
            title_source: "pending" | "generated" | "fallback" | "manual";
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "archived" | "ephemeral";
            /** Parent Thread Id */
            parent_thread_id?: string | null;
            /** Subagent Name */
            subagent_name?: string | null;
            /**
             * Subagent Thread Count
             * @default 0
             */
            subagent_thread_count: number;
            /** Active Run Id */
            active_run_id?: string | null;
            /** Message Count */
            message_count: number;
            /** Compact Count */
            compact_count: number;
            /** Latest State */
            latest_state: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ThreadUpdate
         * @description 重命名会把 title_source 置为 manual —— 之后永不被自动生成覆盖（决策 5）。
         */
        ThreadUpdate: {
            /** Title */
            title?: string | null;
            /** Status */
            status?: ("active" | "archived") | null;
        };
        /** ToolInfo */
        ToolInfo: {
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Display Name */
            display_name: string;
            /** Description */
            description: string;
            /** Available */
            available: boolean;
            /** Note */
            note?: string | null;
            /**
             * Model Tool Names
             * @default []
             */
            model_tool_names: string[];
        };
        /** ToolListResponse */
        ToolListResponse: {
            /** Data */
            data: components["schemas"]["ToolInfo"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_models_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelListResponse"];
                };
            };
        };
    };
    list_tools_v1_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolListResponse"];
                };
            };
        };
    };
    list_agents_v1_agents_get: {
        parameters: {
            query?: {
                /** @description 搜索名称 / 标识 / 描述 */
                q?: string | null;
                status?: string | null;
                /** @description 按模型 id 过滤 */
                model?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_v1_agents_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_v1_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_agent_v1_agents__agent_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_agent_v1_agents__agent_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_agent_status_v1_agents__agent_id__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agent_versions_v1_agents__agent_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentVersionListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_threads_v1_threads_get: {
        parameters: {
            query?: {
                status?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_thread_v1_threads_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThreadCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thread_v1_threads__thread_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_thread_v1_threads__thread_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_thread_v1_threads__thread_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThreadUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_v1_threads__thread_id__runs_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_v1_threads__thread_id__messages_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pending_approvals_v1_runs__run_id__approvals_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingApprovalList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_approval_v1_runs__run_id__approvals__approval_id__post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path: {
                run_id: string;
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_events_v1_runs__run_id__events_get: {
        parameters: {
            query?: {
                after_seq?: number | null;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
