"""用户中心初始表（19 张表的结构）

Revision ID: u0001_initial
Revises:
Create Date: 2026-10-09

主键约定：id 自增主键仅库内使用；uuid 逻辑主键用于全部关联与外键。
内置应用的操作 / 菜单 / 角色不在迁移里，由 `migrate` 之后的 sync_builtin 幂等同步。
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'u0001_initial'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uc_app',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('app_key', sa.String(length=40), nullable=True),
    sa.Column('secret_hash', sa.String(length=64), nullable=True),
    sa.Column('secret_tail', sa.String(length=4), nullable=True),
    sa.Column('secret_rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope_all', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('webhook_secret_enc', sa.LargeBinary(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('active','disabled')", name=op.f('ck_uc_app_status_enum')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uc_app')),
    sa.UniqueConstraint('app_key', name=op.f('uq_uc_app_app_key')),
    sa.UniqueConstraint('name', name=op.f('uq_uc_app_name')),
    sa.UniqueConstraint('uuid', name=op.f('uq_uc_app_uuid'))
    )
    op.create_table('uc_audit_event',
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=8), nullable=False),
    sa.Column('actor_uuid', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_uuid', sa.Uuid(), nullable=True),
    sa.Column('target_name', sa.String(length=200), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uc_audit_event')),
    sa.UniqueConstraint('uuid', name=op.f('uq_uc_audit_event_uuid'))
    )
    op.create_index('ix_uc_audit_event_target', 'uc_audit_event', ['target_type', 'target_uuid'], unique=False)
    op.create_index('ix_uc_audit_event_time', 'uc_audit_event', [sa.literal_column('occurred_at DESC')], unique=False)
    op.create_table('uc_dept',
    sa.Column('parent_uuid', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('leader_uuid', sa.Uuid(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=400), nullable=False),
    sa.Column('depth', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("position('/' in name) = 0", name=op.f('ck_uc_dept_name_no_slash')),
    sa.CheckConstraint('depth BETWEEN 1 AND 10', name=op.f('ck_uc_dept_depth_range')),
    sa.ForeignKeyConstraint(['parent_uuid'], ['uc_dept.uuid'], name=op.f('fk_uc_dept_parent_uuid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uc_dept')),
    sa.UniqueConstraint('parent_uuid', 'name', name='uq_uc_dept_sibling_name'),
    sa.UniqueConstraint('uuid', name=op.f('uq_uc_dept_uuid'))
    )
    op.create_index('ix_uc_dept_parent_sort', 'uc_dept', ['parent_uuid', 'sort'], unique=False)
    op.create_index('ix_uc_dept_path', 'uc_dept', ['path'], unique=False, postgresql_ops={'path': 'varchar_pattern_ops'})
    op.create_index('uq_uc_dept_single_root', 'uc_dept', [sa.literal_column('(parent_uuid IS NULL)')], unique=True, postgresql_where=sa.text('parent_uuid IS NULL'))
    op.create_table('uc_login_log',
    sa.Column('user_uuid', sa.Uuid(), nullable=True),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uc_login_log')),
    sa.UniqueConstraint('uuid', name=op.f('uq_uc_login_log_uuid'))
    )
    op.create_index(op.f('ix_uc_login_log_user_uuid'), 'uc_login_log', ['user_uuid'], unique=False)
    op.create_table('uc_position',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uc_position')),
    sa.UniqueConstraint('code', name=op.f('uq_uc_position_code')),
    sa.UniqueConstraint('name', name=op.f('uq_uc_position_name')),
    sa.UniqueConstraint('uuid', name=op.f('uq_uc_position_uuid'))
    )
    op.create_table('uc_app_scope_dept',
    sa.Column('app_uuid', sa.Uuid(), nullable=False),
    sa.Column('dept_uuid', sa.Uuid(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['app_uuid'], ['uc_app.uuid'], name=op.f('fk_uc_app_scope_dept_app_uuid'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dept_uuid'], ['uc_dept.uuid'], name=op.f('fk_uc_app_scope_dept_dept_uuid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uc_app_scope_dept')),
    sa.UniqueConstraint('app_uuid', 'dept_uuid', name='uq_uc_app_scope'),
    sa.UniqueConstraint('uuid', name=op.f('uq_uc_app_scope_dept_uuid'))
    )
    op.create_table('uc_app_token',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('app_uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['app_uuid'], ['uc_app.uuid'], name=op.f('fk_uc_app_token_app_uuid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uc_app_token')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_uc_app_token_token_hash')),
    sa.UniqueConstraint('uuid', name=op.f('uq_uc_app_token_uuid'))
    )
    op.create_index(op.f('ix_uc_app_token_app_uuid'), 'uc_app_token', ['app_uuid'], unique=False)
    op.create_table('uc_data_type',
    sa.Column('app_uuid', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['app_uuid'], ['uc_app.uuid'], name=op.f('fk_uc_data_type_app_uuid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uc_data_type')),
    sa.UniqueConstraint('code', name=op.f('uq_uc_data_type_code')),
    sa.UniqueConstraint('uuid', name=op.f('uq_uc_data_type_uuid'))
    )
    op.create_table('uc_menu',
    sa.Column('app_uuid', sa.Uuid(), nullable=False),
    sa.Column('parent_uuid', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=True),
    sa.Column('path', sa.String(length=200), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.CheckConstraint("(type = 'menu') = (path IS NOT NULL)", name=op.f('ck_uc_menu_path_iff_menu')),
    sa.CheckConstraint("type = 'menu' OR NOT is_public", name=op.f('ck_uc_menu_public_only_menu')),
    sa.CheckConstraint("type IN ('dir','menu')", name=op.f('ck_uc_menu_type_enum')),
    sa.ForeignKeyConstraint(['app_uuid'], ['uc_app.uuid'], name=op.f('fk_uc_menu_app_uuid')),
    sa.ForeignKeyConstraint(['parent_uuid'], ['uc_menu.uuid'], name=op.f('fk_uc_menu_parent_uuid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uc_menu')),
    sa.UniqueConstraint('app_uuid', 'code', name='uq_uc_menu_code'),
    sa.UniqueConstraint('uuid', name=op.f('uq_uc_menu_uuid'))
    )
    op.create_index('uq_uc_menu_path', 'uc_menu', ['app_uuid', 'path'], unique=True, postgresql_where=sa.text('path IS NOT NULL'))
    op.create_table('uc_operation',
    sa.Column('app_uuid', sa.Uuid(), nullable=False),
    sa.Column('module', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['app_uuid'], ['uc_app.uuid'], name=op.f('fk_uc_operation_app_uuid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uc_operation')),
    sa.UniqueConstraint('app_uuid', 'code', name='uq_uc_operation_code'),
    sa.UniqueConstraint('uuid', name=op.f('uq_uc_operation_uuid'))
    )
    op.create_table('uc_role',
    sa.Column('app_uuid', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_uuid'], ['uc_app.uuid'], name=op.f('fk_uc_role_app_uuid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uc_role')),
    sa.UniqueConstraint('app_uuid', 'name', name='uq_uc_role_name'),
    sa.UniqueConstraint('code', name=op.f('uq_uc_role_code')),
    sa.UniqueConstraint('uuid', name=op.f('uq_uc_role_uuid'))
    )
    op.create_table('uc_user',
    sa.Column('account', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('dept_uuid', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_by', sa.Uuid(), nullable=True),
    sa.Column('disabled_reason', sa.String(length=200), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('active','disabled')", name=op.f('ck_uc_user_status_enum')),
    sa.ForeignKeyConstraint(['dept_uuid'], ['uc_dept.uuid'], name=op.f('fk_uc_user_dept_uuid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uc_user')),
    sa.UniqueConstraint('account', name=op.f('uq_uc_user_account')),
    sa.UniqueConstraint('email', name=op.f('uq_uc_user_email')),
    sa.UniqueConstraint('uuid', name=op.f('uq_uc_user_uuid'))
    )
    op.create_index(op.f('ix_uc_user_dept_uuid'), 'uc_user', ['dept_uuid'], unique=False)
    op.create_table('uc_data_object',
    sa.Column('data_type_uuid', sa.Uuid(), nullable=False),
    sa.Column('data_id', sa.String(length=64), nullable=False),
    sa.Column('data_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['data_type_uuid'], ['uc_data_type.uuid'], name=op.f('fk_uc_data_object_data_type_uuid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uc_data_object')),
    sa.UniqueConstraint('data_type_uuid', 'data_id', name='uq_uc_data_object'),
    sa.UniqueConstraint('uuid', name=op.f('uq_uc_data_object_uuid'))
    )
    op.create_table('uc_grant',
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('position_uuid', sa.Uuid(), nullable=True),
    sa.Column('role_uuid', sa.Uuid(), nullable=True),
    sa.Column('subject_type', sa.String(length=8), nullable=False),
    sa.Column('user_uuid', sa.Uuid(), nullable=True),
    sa.Column('dept_uuid', sa.Uuid(), nullable=True),
    sa.Column('include_sub', sa.Boolean(), nullable=False),
    sa.Column('granted_by', sa.Uuid(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.CheckConstraint("((kind = 'position') = (position_uuid IS NOT NULL)) AND ((kind = 'role') = (role_uuid IS NOT NULL))", name=op.f('ck_uc_grant_kind_target')),
    sa.CheckConstraint("((subject_type = 'user') = (user_uuid IS NOT NULL)) AND ((subject_type = 'dept') = (dept_uuid IS NOT NULL))", name=op.f('ck_uc_grant_subject')),
    sa.CheckConstraint("subject_type = 'dept' OR NOT include_sub", name=op.f('ck_uc_grant_sub_only_dept')),
    sa.ForeignKeyConstraint(['dept_uuid'], ['uc_dept.uuid'], name=op.f('fk_uc_grant_dept_uuid'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_uuid'], ['uc_position.uuid'], name=op.f('fk_uc_grant_position_uuid')),
    sa.ForeignKeyConstraint(['role_uuid'], ['uc_role.uuid'], name=op.f('fk_uc_grant_role_uuid'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['uc_user.uuid'], name=op.f('fk_uc_grant_user_uuid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uc_grant')),
    sa.UniqueConstraint('uuid', name=op.f('uq_uc_grant_uuid'))
    )
    op.create_index('ix_uc_grant_dept', 'uc_grant', ['dept_uuid'], unique=False, postgresql_where=sa.text('dept_uuid IS NOT NULL'))
    op.create_index('ix_uc_grant_pos', 'uc_grant', ['position_uuid'], unique=False, postgresql_where=sa.text('position_uuid IS NOT NULL'))
    op.create_index('ix_uc_grant_role', 'uc_grant', ['role_uuid'], unique=False, postgresql_where=sa.text('role_uuid IS NOT NULL'))
    op.create_index('ix_uc_grant_user', 'uc_grant', ['user_uuid'], unique=False, postgresql_where=sa.text('user_uuid IS NOT NULL'))
    op.create_index('uq_uc_grant', 'uc_grant', ['kind', sa.literal_column('coalesce(position_uuid, role_uuid)'), sa.literal_column('coalesce(user_uuid, dept_uuid)')], unique=True)
    op.create_table('uc_position_role',
    sa.Column('position_uuid', sa.Uuid(), nullable=False),
    sa.Column('role_uuid', sa.Uuid(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['position_uuid'], ['uc_position.uuid'], name=op.f('fk_uc_position_role_position_uuid'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_uuid'], ['uc_role.uuid'], name=op.f('fk_uc_position_role_role_uuid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uc_position_role')),
    sa.UniqueConstraint('position_uuid', 'role_uuid', name='uq_uc_position_role'),
    sa.UniqueConstraint('uuid', name=op.f('uq_uc_position_role_uuid'))
    )
    op.create_table('uc_role_menu',
    sa.Column('role_uuid', sa.Uuid(), nullable=False),
    sa.Column('menu_uuid', sa.Uuid(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['menu_uuid'], ['uc_menu.uuid'], name=op.f('fk_uc_role_menu_menu_uuid'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_uuid'], ['uc_role.uuid'], name=op.f('fk_uc_role_menu_role_uuid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uc_role_menu')),
    sa.UniqueConstraint('role_uuid', 'menu_uuid', name='uq_uc_role_menu'),
    sa.UniqueConstraint('uuid', name=op.f('uq_uc_role_menu_uuid'))
    )
    op.create_table('uc_role_operation',
    sa.Column('role_uuid', sa.Uuid(), nullable=False),
    sa.Column('operation_uuid', sa.Uuid(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['operation_uuid'], ['uc_operation.uuid'], name=op.f('fk_uc_role_operation_operation_uuid'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_uuid'], ['uc_role.uuid'], name=op.f('fk_uc_role_operation_role_uuid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uc_role_operation')),
    sa.UniqueConstraint('role_uuid', 'operation_uuid', name='uq_uc_role_op'),
    sa.UniqueConstraint('uuid', name=op.f('uq_uc_role_operation_uuid'))
    )
    op.create_table('uc_session',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['uc_user.uuid'], name=op.f('fk_uc_session_user_uuid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uc_session')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_uc_session_token_hash')),
    sa.UniqueConstraint('uuid', name=op.f('uq_uc_session_uuid'))
    )
    op.create_index(op.f('ix_uc_session_user_uuid'), 'uc_session', ['user_uuid'], unique=False)
    op.create_table('uc_user_credential',
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('temp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['uc_user.uuid'], name=op.f('fk_uc_user_credential_user_uuid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uc_user_credential')),
    sa.UniqueConstraint('user_uuid', name=op.f('uq_uc_user_credential_user_uuid')),
    sa.UniqueConstraint('uuid', name=op.f('uq_uc_user_credential_uuid'))
    )
    op.create_table('uc_data_acl',
    sa.Column('data_object_uuid', sa.Uuid(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('subject_type', sa.String(length=8), nullable=False),
    sa.Column('user_uuid', sa.Uuid(), nullable=True),
    sa.Column('dept_uuid', sa.Uuid(), nullable=True),
    sa.Column('include_sub', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('granted_by', sa.Uuid(), nullable=True),
    sa.Column('granted_app_uuid', sa.Uuid(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.CheckConstraint("((subject_type = 'user') = (user_uuid IS NOT NULL)) AND ((subject_type = 'dept') = (dept_uuid IS NOT NULL))", name=op.f('ck_uc_data_acl_subject')),
    sa.CheckConstraint("subject_type = 'dept' OR NOT include_sub", name=op.f('ck_uc_data_acl_sub_only_dept')),
    sa.CheckConstraint('level IN (1, 2, 3)', name=op.f('ck_uc_data_acl_level_enum')),
    sa.ForeignKeyConstraint(['data_object_uuid'], ['uc_data_object.uuid'], name=op.f('fk_uc_data_acl_data_object_uuid'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dept_uuid'], ['uc_dept.uuid'], name=op.f('fk_uc_data_acl_dept_uuid'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['uc_user.uuid'], name=op.f('fk_uc_data_acl_user_uuid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uc_data_acl')),
    sa.UniqueConstraint('uuid', name=op.f('uq_uc_data_acl_uuid'))
    )
    op.create_index('ix_uc_data_acl_dept', 'uc_data_acl', ['dept_uuid'], unique=False, postgresql_where=sa.text('dept_uuid IS NOT NULL'))
    op.create_index('ix_uc_data_acl_user', 'uc_data_acl', ['user_uuid'], unique=False, postgresql_where=sa.text('user_uuid IS NOT NULL'))
    op.create_index('uq_uc_data_acl', 'uc_data_acl', ['data_object_uuid', sa.literal_column('coalesce(user_uuid, dept_uuid)')], unique=True)
    # uc_dept.leader_uuid 与 uc_user.dept_uuid 互相引用：两表都建好后再补这条外键
    op.create_foreign_key('fk_uc_dept_leader_uuid', 'uc_dept', 'uc_user', ['leader_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_uc_dept_leader_uuid', 'uc_dept', type_='foreignkey')
    op.drop_index('uq_uc_data_acl', table_name='uc_data_acl')
    op.drop_index('ix_uc_data_acl_user', table_name='uc_data_acl', postgresql_where=sa.text('user_uuid IS NOT NULL'))
    op.drop_index('ix_uc_data_acl_dept', table_name='uc_data_acl', postgresql_where=sa.text('dept_uuid IS NOT NULL'))
    op.drop_table('uc_data_acl')
    op.drop_table('uc_user_credential')
    op.drop_index(op.f('ix_uc_session_user_uuid'), table_name='uc_session')
    op.drop_table('uc_session')
    op.drop_table('uc_role_operation')
    op.drop_table('uc_role_menu')
    op.drop_table('uc_position_role')
    op.drop_index('uq_uc_grant', table_name='uc_grant')
    op.drop_index('ix_uc_grant_user', table_name='uc_grant', postgresql_where=sa.text('user_uuid IS NOT NULL'))
    op.drop_index('ix_uc_grant_role', table_name='uc_grant', postgresql_where=sa.text('role_uuid IS NOT NULL'))
    op.drop_index('ix_uc_grant_pos', table_name='uc_grant', postgresql_where=sa.text('position_uuid IS NOT NULL'))
    op.drop_index('ix_uc_grant_dept', table_name='uc_grant', postgresql_where=sa.text('dept_uuid IS NOT NULL'))
    op.drop_table('uc_grant')
    op.drop_table('uc_data_object')
    op.drop_index(op.f('ix_uc_user_dept_uuid'), table_name='uc_user')
    op.drop_table('uc_user')
    op.drop_table('uc_role')
    op.drop_table('uc_operation')
    op.drop_index('uq_uc_menu_path', table_name='uc_menu', postgresql_where=sa.text('path IS NOT NULL'))
    op.drop_table('uc_menu')
    op.drop_table('uc_data_type')
    op.drop_index(op.f('ix_uc_app_token_app_uuid'), table_name='uc_app_token')
    op.drop_table('uc_app_token')
    op.drop_table('uc_app_scope_dept')
    op.drop_table('uc_position')
    op.drop_index(op.f('ix_uc_login_log_user_uuid'), table_name='uc_login_log')
    op.drop_table('uc_login_log')
    op.drop_index('uq_uc_dept_single_root', table_name='uc_dept', postgresql_where=sa.text('parent_uuid IS NULL'))
    op.drop_index('ix_uc_dept_path', table_name='uc_dept', postgresql_ops={'path': 'varchar_pattern_ops'})
    op.drop_index('ix_uc_dept_parent_sort', table_name='uc_dept')
    op.drop_table('uc_dept')
    op.drop_index('ix_uc_audit_event_time', table_name='uc_audit_event')
    op.drop_index('ix_uc_audit_event_target', table_name='uc_audit_event')
    op.drop_table('uc_audit_event')
    op.drop_table('uc_app')
    # ### end Alembic commands ###
