"""process_runtime

Revision ID: t0002
Revises: t0001
Create Date: 2026-10-09 17:13:30.624394
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 't0002'
down_revision: str | Sequence[str] | None = 't0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tf_process',
    sa.Column('team_uuid', sa.Uuid(), nullable=False),
    sa.Column('project_uuid', sa.Uuid(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('template_uuid', sa.Uuid(), nullable=False),
    sa.Column('template_version_uuid', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_by', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_seq', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('running','completed','terminated')", name=op.f('ck_tf_process_status_enum')),
    sa.ForeignKeyConstraint(['project_uuid'], ['tf_project.uuid'], name=op.f('fk_tf_process_project_uuid')),
    sa.ForeignKeyConstraint(['team_uuid'], ['tf_team.uuid'], name=op.f('fk_tf_process_team_uuid')),
    sa.ForeignKeyConstraint(['template_version_uuid'], ['tf_flow_template_version.uuid'], name=op.f('fk_tf_process_template_version_uuid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tf_process')),
    sa.UniqueConstraint('project_uuid', 'no', name='uq_tf_process_no'),
    sa.UniqueConstraint('uuid', name=op.f('uq_tf_process_uuid'))
    )
    op.create_index(op.f('ix_tf_process_project_uuid'), 'tf_process', ['project_uuid'], unique=False)
    op.create_index(op.f('ix_tf_process_team_uuid'), 'tf_process', ['team_uuid'], unique=False)
    op.create_table('tf_process_event',
    sa.Column('process_uuid', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('node_id', sa.String(length=32), nullable=True),
    sa.Column('actor_uuid', sa.Uuid(), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['process_uuid'], ['tf_process.uuid'], name=op.f('fk_tf_process_event_process_uuid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tf_process_event')),
    sa.UniqueConstraint('process_uuid', 'seq', name='uq_tf_process_event_seq'),
    sa.UniqueConstraint('uuid', name=op.f('uq_tf_process_event_uuid'))
    )
    op.create_table('tf_process_node',
    sa.Column('process_uuid', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('exec_role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('file_template_version_uuid', sa.Uuid(), nullable=True),
    sa.Column('agent_uuid', sa.Uuid(), nullable=True),
    sa.Column('atlas_agent_id', sa.String(length=64), nullable=True),
    sa.Column('atlas_thread_id', sa.String(length=64), nullable=True),
    sa.Column('atlas_cursor', sa.Integer(), nullable=False),
    sa.Column('atlas_run_id', sa.String(length=64), nullable=True),
    sa.Column('notice', sa.String(length=200), nullable=True),
    sa.Column('current_artifact_uuid', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('passed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('pending','working','exit_review','admit_review','passed','returned')", name=op.f('ck_tf_process_node_status_enum')),
    sa.ForeignKeyConstraint(['process_uuid'], ['tf_process.uuid'], name=op.f('fk_tf_process_node_process_uuid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tf_process_node')),
    sa.UniqueConstraint('process_uuid', 'node_id', name='uq_tf_process_node'),
    sa.UniqueConstraint('uuid', name=op.f('uq_tf_process_node_uuid'))
    )
    op.create_index(op.f('ix_tf_process_node_process_uuid'), 'tf_process_node', ['process_uuid'], unique=False)
    op.create_table('tf_artifact_version',
    sa.Column('node_uuid', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['node_uuid'], ['tf_process_node.uuid'], name=op.f('fk_tf_artifact_version_node_uuid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tf_artifact_version')),
    sa.UniqueConstraint('node_uuid', 'version_no', name='uq_tf_artifact_no'),
    sa.UniqueConstraint('uuid', name=op.f('uq_tf_artifact_version_uuid'))
    )
    op.create_index(op.f('ix_tf_artifact_version_node_uuid'), 'tf_artifact_version', ['node_uuid'], unique=False)
    op.create_table('tf_node_message',
    sa.Column('node_uuid', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=8), nullable=False),
    sa.Column('author_uuid', sa.Uuid(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('atlas_run_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['node_uuid'], ['tf_process_node.uuid'], name=op.f('fk_tf_node_message_node_uuid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tf_node_message')),
    sa.UniqueConstraint('uuid', name=op.f('uq_tf_node_message_uuid'))
    )
    op.create_index(op.f('ix_tf_node_message_node_uuid'), 'tf_node_message', ['node_uuid'], unique=False)
    op.create_table('tf_review_round',
    sa.Column('node_uuid', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=8), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('rule', sa.String(length=4), nullable=False),
    sa.Column('reviewers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('artifact_uuid', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['node_uuid'], ['tf_process_node.uuid'], name=op.f('fk_tf_review_round_node_uuid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tf_review_round')),
    sa.UniqueConstraint('uuid', name=op.f('uq_tf_review_round_uuid'))
    )
    op.create_index(op.f('ix_tf_review_round_node_uuid'), 'tf_review_round', ['node_uuid'], unique=False)
    op.create_table('tf_vote',
    sa.Column('review_uuid', sa.Uuid(), nullable=False),
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=8), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('return_to', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['review_uuid'], ['tf_review_round.uuid'], name=op.f('fk_tf_vote_review_uuid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tf_vote')),
    sa.UniqueConstraint('review_uuid', 'user_uuid', name='uq_tf_vote'),
    sa.UniqueConstraint('uuid', name=op.f('uq_tf_vote_uuid'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tf_vote')
    op.drop_index(op.f('ix_tf_review_round_node_uuid'), table_name='tf_review_round')
    op.drop_table('tf_review_round')
    op.drop_index(op.f('ix_tf_node_message_node_uuid'), table_name='tf_node_message')
    op.drop_table('tf_node_message')
    op.drop_index(op.f('ix_tf_artifact_version_node_uuid'), table_name='tf_artifact_version')
    op.drop_table('tf_artifact_version')
    op.drop_index(op.f('ix_tf_process_node_process_uuid'), table_name='tf_process_node')
    op.drop_table('tf_process_node')
    op.drop_table('tf_process_event')
    op.drop_index(op.f('ix_tf_process_team_uuid'), table_name='tf_process')
    op.drop_index(op.f('ix_tf_process_project_uuid'), table_name='tf_process')
    op.drop_table('tf_process')
    # ### end Alembic commands ###
