"""initial

Revision ID: t0001
Revises: 
Create Date: 2026-10-09 16:12:15.348726
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 't0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tf_audit_event',
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_uuid', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_uuid', sa.Uuid(), nullable=True),
    sa.Column('target_name', sa.String(length=200), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tf_audit_event')),
    sa.UniqueConstraint('uuid', name=op.f('uq_tf_audit_event_uuid'))
    )
    op.create_index('ix_tf_audit_event_target', 'tf_audit_event', ['target_type', 'target_uuid'], unique=False)
    op.create_index('ix_tf_audit_event_time', 'tf_audit_event', [sa.literal_column('occurred_at DESC')], unique=False)
    op.create_table('tf_file_template',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('usage', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_version_uuid', sa.Uuid(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('active','disabled')", name=op.f('ck_tf_file_template_status_enum')),
    sa.CheckConstraint("usage IN ('artifact','review_rule','other')", name=op.f('ck_tf_file_template_usage_enum')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tf_file_template')),
    sa.UniqueConstraint('name', name=op.f('uq_tf_file_template_name')),
    sa.UniqueConstraint('uuid', name=op.f('uq_tf_file_template_uuid'))
    )
    op.create_table('tf_flow_role',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tf_flow_role')),
    sa.UniqueConstraint('name', name=op.f('uq_tf_flow_role_name')),
    sa.UniqueConstraint('uuid', name=op.f('uq_tf_flow_role_uuid'))
    )
    op.create_table('tf_flow_template',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(length=200), nullable=True),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_version_uuid', sa.Uuid(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('active','disabled')", name=op.f('ck_tf_flow_template_status_enum')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tf_flow_template')),
    sa.UniqueConstraint('name', name=op.f('uq_tf_flow_template_name')),
    sa.UniqueConstraint('uuid', name=op.f('uq_tf_flow_template_uuid'))
    )
    op.create_table('tf_team',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('active','archived')", name=op.f('ck_tf_team_status_enum')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tf_team')),
    sa.UniqueConstraint('name', name=op.f('uq_tf_team_name')),
    sa.UniqueConstraint('uuid', name=op.f('uq_tf_team_uuid'))
    )
    op.create_table('tf_user',
    sa.Column('account', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tf_user')),
    sa.UniqueConstraint('account', name=op.f('uq_tf_user_account')),
    sa.UniqueConstraint('uuid', name=op.f('uq_tf_user_uuid'))
    )
    op.create_table('tf_file_template_version',
    sa.Column('template_uuid', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('change_note', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['template_uuid'], ['tf_file_template.uuid'], name=op.f('fk_tf_file_template_version_template_uuid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tf_file_template_version')),
    sa.UniqueConstraint('template_uuid', 'version_no', name='uq_tf_ftv_no'),
    sa.UniqueConstraint('uuid', name=op.f('uq_tf_file_template_version_uuid'))
    )
    op.create_table('tf_flow_template_draft',
    sa.Column('template_uuid', sa.Uuid(), nullable=False),
    sa.Column('base_version_uuid', sa.Uuid(), nullable=True),
    sa.Column('definition', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('editor_uuid', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['template_uuid'], ['tf_flow_template.uuid'], name=op.f('fk_tf_flow_template_draft_template_uuid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tf_flow_template_draft')),
    sa.UniqueConstraint('template_uuid', name=op.f('uq_tf_flow_template_draft_template_uuid')),
    sa.UniqueConstraint('uuid', name=op.f('uq_tf_flow_template_draft_uuid'))
    )
    op.create_table('tf_flow_template_version',
    sa.Column('template_uuid', sa.Uuid(), nullable=False),
    sa.Column('major', sa.Integer(), nullable=False),
    sa.Column('minor', sa.Integer(), nullable=False),
    sa.Column('definition', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('roles', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('change_note', sa.String(length=500), nullable=False),
    sa.Column('published_by', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['template_uuid'], ['tf_flow_template.uuid'], name=op.f('fk_tf_flow_template_version_template_uuid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tf_flow_template_version')),
    sa.UniqueConstraint('template_uuid', 'major', 'minor', name='uq_tf_flow_version'),
    sa.UniqueConstraint('uuid', name=op.f('uq_tf_flow_template_version_uuid'))
    )
    op.create_table('tf_project',
    sa.Column('team_uuid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('flow_template_uuid', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('active','archived')", name=op.f('ck_tf_project_status_enum')),
    sa.ForeignKeyConstraint(['flow_template_uuid'], ['tf_flow_template.uuid'], name=op.f('fk_tf_project_flow_template_uuid')),
    sa.ForeignKeyConstraint(['team_uuid'], ['tf_team.uuid'], name=op.f('fk_tf_project_team_uuid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tf_project')),
    sa.UniqueConstraint('team_uuid', 'name', name='uq_tf_project_name'),
    sa.UniqueConstraint('uuid', name=op.f('uq_tf_project_uuid'))
    )
    op.create_index(op.f('ix_tf_project_team_uuid'), 'tf_project', ['team_uuid'], unique=False)
    op.create_table('tf_session',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['tf_user.uuid'], name=op.f('fk_tf_session_user_uuid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tf_session')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_tf_session_token_hash')),
    sa.UniqueConstraint('uuid', name=op.f('uq_tf_session_uuid'))
    )
    op.create_index(op.f('ix_tf_session_user_uuid'), 'tf_session', ['user_uuid'], unique=False)
    op.create_table('tf_team_agent',
    sa.Column('team_uuid', sa.Uuid(), nullable=False),
    sa.Column('atlas_agent_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('avatar_key', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('added_by', sa.Uuid(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['team_uuid'], ['tf_team.uuid'], name=op.f('fk_tf_team_agent_team_uuid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tf_team_agent')),
    sa.UniqueConstraint('team_uuid', 'atlas_agent_id', name='uq_tf_team_agent'),
    sa.UniqueConstraint('uuid', name=op.f('uq_tf_team_agent_uuid'))
    )
    op.create_table('tf_project_role_assignment',
    sa.Column('project_uuid', sa.Uuid(), nullable=False),
    sa.Column('role_name', sa.String(length=32), nullable=False),
    sa.Column('assignee_type', sa.String(length=8), nullable=False),
    sa.Column('assignee_uuid', sa.Uuid(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.CheckConstraint("assignee_type IN ('user','agent')", name=op.f('ck_tf_project_role_assignment_assignee_type_enum')),
    sa.ForeignKeyConstraint(['project_uuid'], ['tf_project.uuid'], name=op.f('fk_tf_project_role_assignment_project_uuid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tf_project_role_assignment')),
    sa.UniqueConstraint('project_uuid', 'role_name', 'assignee_type', 'assignee_uuid', name='uq_tf_assignment'),
    sa.UniqueConstraint('uuid', name=op.f('uq_tf_project_role_assignment_uuid'))
    )
    op.create_index('ix_tf_assignment_project_role', 'tf_project_role_assignment', ['project_uuid', 'role_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tf_assignment_project_role', table_name='tf_project_role_assignment')
    op.drop_table('tf_project_role_assignment')
    op.drop_table('tf_team_agent')
    op.drop_index(op.f('ix_tf_session_user_uuid'), table_name='tf_session')
    op.drop_table('tf_session')
    op.drop_index(op.f('ix_tf_project_team_uuid'), table_name='tf_project')
    op.drop_table('tf_project')
    op.drop_table('tf_flow_template_version')
    op.drop_table('tf_flow_template_draft')
    op.drop_table('tf_file_template_version')
    op.drop_table('tf_user')
    op.drop_table('tf_team')
    op.drop_table('tf_flow_template')
    op.drop_table('tf_flow_role')
    op.drop_table('tf_file_template')
    op.drop_index('ix_tf_audit_event_time', table_name='tf_audit_event')
    op.drop_index('ix_tf_audit_event_target', table_name='tf_audit_event')
    op.drop_table('tf_audit_event')
    # ### end Alembic commands ###
